### ISSUE TITLE
usage of previously freed memory

### ISSUE THREAD

**Issue by parihaaraka** [igron99/tarantool-cpp#5]
```
tnt_reply_free(reply);
throw std::runtime_error(reply->error);
```
You'd prefer unique_ptr with custom deleter (it's zero cost compared to raw pointers)
```
using tnt_s_stream = std::unique_ptr<struct tnt_stream, void(*)(struct tnt_stream*)>;
using tnt_s_request = std::unique_ptr<struct tnt_request, void(*)(struct tnt_request*)>;
using tnt_s_reply = std::unique_ptr<struct tnt_reply, void(*)(struct tnt_reply*)>;
...
tnt_s_stream stream{tnt_object(nullptr), tnt_stream_free};
tnt_s_request request(tnt_request_call(nullptr), tnt_request_free);
tnt_s_reply reply{tnt_reply_init(nullptr), tnt_reply_free};
```
to avoid all the following leakage risks and simplify the code.

You have CMAKE_CXX_STANDARD 17 but use boost (?). std::optional is in standard library since C++17.

**Comment by ObjatieGroba** [comment]
Hello, thank you
I will wrap c structs
Yes, I am. I know about optional, but I had the task from my boss)
std::optional, std::map (unordered too), std::pair, std::list (all types) stream methods would be done as soon as possible.

**Comment by parihaaraka** [comment]
* I beg your pardon for offtop
Take a look at https://github.com/parihaaraka/pgpp
It contains db-agnostic dbpool.h. We could get it in Tarantool connector to make things easier ;)

**Comment by ObjatieGroba** [comment]
> * I beg your pardon for offtop
>   Take a look at https://github.com/parihaaraka/pgpp
>   It contains db-agnostic dbpool.h. We could get it in Tarantool connector to make things easier ;)

Hm, good idea. I need more time to think about it.
